name: Docker Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@0788c444d8b4d67580213712e34a148cae3a6c4e
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: thomasfire/atomiki:latest
