name: Docker Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Build Docker image
        uses: docker/build-push-action@55146d969b0dff1a5c12630229609757af5b1081
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: thomasfire/atomiki:latest
