
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: actions-setup-redis
      uses: shogo82148/actions-setup-redis@v1.37.0
      with:
        redis-port: 6379
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Build frontend app
      run: |
        cd app
        npm install
        npm run build
        cd ..
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run unittests
      run: mvn test
    - name: Run spring boot app
      run: mvn spring-boot:run &
    - name: Wait for app server started
      run: while ! grep -m1 'Started AtomikiApplication' atomiki.log; do sleep 1; done
    - name: Run auto tests on node
      run: |
        cd src/test/js
        npm install
        npm run test
    - name: Stop server
      run: mvn spring-boot:stop
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: target/atomiki-*.jar
