# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: actions-setup-redis
      uses: shogo82148/actions-setup-redis@v1.33.0
      with:
        redis-port: 6379
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run unittests
      run: mvn test
    - name: Run spring boot app
      run: mvn spring-boot:run &
    - name: Wait for app server started
      run: while ! grep -m1 'Started AtomikiApplication' atomiki.log; do sleep 1; done
    - name: Set up Node for tests
      run: |
        cd src/test/js
        npm install
    - name: Run autotests
      run: npm run test
